Document: seismic-unix
Title: Debian seismic-unix Manual
Author: <insert document author here>
Abstract: This manual describes what seismic-unix is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/seismic-unix/seismic-unix.sgml.gz

Format: postscript
Files: /usr/share/doc/seismic-unix/seismic-unix.ps.gz

Format: text
Files: /usr/share/doc/seismic-unix/seismic-unix.text.gz

Format: HTML
Index: /usr/share/doc/seismic-unix/html/index.html
Files: /usr/share/doc/seismic-unix/html/*.html
